services:
  - type: web
    name: dinnerschool
    env: python
    plan: free
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn DinnerSchool.mysite.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /admin/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dinnerschool_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,dinnerschool.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "mysite.settings"

databases:
  - name: dinnerschool_db
    databaseName: dinnerschool_db
    user: dinnerschool_db_user
    plan: free