services:
  - type: web
    name: dinnerschool
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT DinnerSchool.mysite.wsgi:application"
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dinnerschool-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: dinnerschool-db
    databaseName: dinnerschool_db
    user: dinnerschool_user
    plan: free