build:
  pythonVersion: 3.11.6
services:
  - type: web
    name: dinnerschool-marco
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT DinnerSchool.mysite.wsgi:application"
    plan: free
    branch: main
    healthCheckPath: /admin/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dinnerschool_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,dinnerschool-marco.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "mysite.settings"

databases:
  - name: dinnerschool_db
    databaseName: dinnerschool_production
    user: marco_user
    plan: free