# Generated by Django 4.2.23 on 2025-07-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_niveleducativo_grupo_alter_niveleducativo_grado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingredientes', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pendiente'), (1, 'En preparación'), (2, 'Listo'), (3, 'Entregado'), (4, 'Cancelado')], default=0)),
                ('turno', models.PositiveIntegerField(choices=[(0, 'Desayuno'), (1, 'Comida')], default=0)),
                ('alumnoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumnos')),
                ('nivelEducativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveleducativo')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.platillo')),
            ],
        ),
        migrations.CreateModel(
            name='CreditoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
    ]
