# Generated by Django 4.2.23 on 2025-07-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creditodiario',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comedor.pedido'),
        ),
    ]
