# Generated by Django 4.2.23 on 2025-08-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0003_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ingredientePlatillo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
