# Generated by Django 4.2.23 on 2025-08-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alumnos_options_alter_empleados_options_and_more'),
        ('comedor', '0004_pedido_ingredienteplatillo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credito',
            options={'verbose_name': 'Crédito', 'verbose_name_plural': 'Créditos'},
        ),
        migrations.AlterModelOptions(
            name='creditodiario',
            options={'verbose_name': 'Crédito Diario', 'verbose_name_plural': 'Créditos Diarios'},
        ),
        migrations.AlterModelOptions(
            name='ingredientes',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='platillo',
            options={'verbose_name': 'Platillo', 'verbose_name_plural': 'Platillos'},
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='tutorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='creditodiario',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='creditodiario',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='creditodiario',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comedor.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='creditodiario',
            name='tutorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='alumnoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumnos', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ingredientePlatillo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ingredientes del Platillo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nivelEducativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveleducativo', verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nota',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.platillo', verbose_name='Platillo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pendiente'), (1, 'En preparación'), (2, 'Listo'), (3, 'Entregado'), (4, 'Cancelado')], default=0, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='turno',
            field=models.PositiveIntegerField(choices=[(0, 'Desayuno'), (1, 'Comida')], default=0, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='ingredientes',
            field=models.CharField(max_length=200, verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
