# Generated by Django 4.2.23 on 2025-08-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alumnos_options_alter_empleados_options_and_more'),
        ('comedor', '0005_alter_credito_options_alter_creditodiario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='alumnoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alumnos', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nivelEducativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.niveleducativo', verbose_name='Nivel Educativo'),
        ),
    ]
