# Generated by Django 4.2.23 on 2025-08-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alumnos_options_alter_empleados_options_and_more'),
        ('comedor', '0006_alter_pedido_alumnoid_alter_pedido_niveleducativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='profesorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleados', verbose_name='Profesor'),
        ),
    ]
