# Generated by Django 4.2.23 on 2025-08-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alumnos_options_alter_empleados_options_and_more'),
        ('comedor', '0007_pedido_profesorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='encargadoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado_pedidos', to='core.empleados', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='profesorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_pedidos', to='core.empleados', verbose_name='Profesor'),
        ),
    ]
