# Generated by Django 4.2.23 on 2025-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0008_pedido_encargadoid_alter_pedido_profesorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='tipoAnuncio',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aviso'), (2, 'Urgente'), (3, 'Recordatorio')], default=1, verbose_name='Tipo de Anuncio'),
        ),
    ]
