# Generated by Django 4.2.23 on 2025-08-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alumnos_options_alter_empleados_options_and_more'),
        ('comedor', '0009_noticias_tipoanuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='profesorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleados', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='tipoAnuncio',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Recordatorio'), (1, 'Urgente'), (2, 'Aviso')], default=1, verbose_name='Tipo de Anuncio'),
        ),
    ]
