# Generated by Django 4.2.23 on 2025-08-22 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alumnos_options_alter_empleados_options_and_more'),
        ('comedor', '0010_credito_profesorid_alter_noticias_tipoanuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='tutorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tutor', verbose_name='Tutor'),
        ),
    ]
