# Generated by Django 4.2.23 on 2025-08-22 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alumnos_options_alter_empleados_options_and_more'),
        ('comedor', '0011_alter_credito_tutorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditodiario',
            name='profesorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleados', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='creditodiario',
            name='tutorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tutor', verbose_name='Tutor'),
        ),
    ]
