# Generated by Django 4.2.23 on 2025-08-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0012_creditodiario_profesorid_alter_creditodiario_tutorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='turno',
            field=models.PositiveIntegerField(choices=[(0, 'Reseso 1'), (1, 'Reseso 2'), (2, 'Comida')], default=0, verbose_name='Turno'),
        ),
    ]
