# Generated by Django 4.2.23 on 2025-08-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0014_alter_credito_profesorid_alter_credito_tutorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
