# Generated by Django 4.2.23 on 2025-09-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0015_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comedor.platillo', verbose_name='Platillo'),
        ),
    ]
