# Generated by Django 4.2.23 on 2025-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0016_alter_pedido_platillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
