# Generated by Django 4.2.23 on 2025-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0017_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nota',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Nota'),
        ),
    ]
