# Generated by Django 4.2.23 on 2025-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0018_alter_pedido_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ingredientePlatillo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ingredientes del Platillo'),
        ),
    ]
