# Generated by Django 4.2.23 on 2025-09-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0019_alter_pedido_ingredienteplatillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='rutaImagen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen'),
        ),
    ]
