# Generated by Django 4.2.23 on 2025-09-08 23:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0020_noticias_rutaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='rutaImagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
