# Generated by Django 4.2.23 on 2025-09-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0021_alter_noticias_rutaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
