# Generated by Django 4.2.23 on 2025-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0022_platillo_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='creditodiario',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
