# Generated by Django 4.0.10 on 2025-11-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0023_alter_credito_fecha_alter_creditodiario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='creado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
    ]
