# Generated by Django 6.0 on 2026-08-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0024_pedido_creado'),
        ('core', '0007_add_verificacion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.PositiveIntegerField(choices=[(0, 'Reseso 1'), (1, 'Reseso 2'), (2, 'Comida')], default=0, verbose_name='Turno')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pendiente'), (1, 'En preparación'), (2, 'Listo'), (3, 'Entregado'), (4, 'Cancelado')], default=0, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('alumnoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alumnos', verbose_name='Alumno')),
                ('encargadoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado_ordenes', to='core.empleados', verbose_name='Encargado')),
                ('nivelEducativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.niveleducativo', verbose_name='Nivel Educativo')),
                ('profesorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_ordenes', to='core.empleados', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comedor.orden', verbose_name='Orden'),
        ),
    ]
