# Generated by Django 6.0 on 2026-08-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0025_add_orden_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='clienteNombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='esVentaDirecta',
            field=models.BooleanField(default=False, verbose_name='Venta Directa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='esVentaDirecta',
            field=models.BooleanField(default=False, verbose_name='Venta Directa'),
        ),
    ]
