# Generated by Django 4.2.23 on 2025-07-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(choices=[('1', 'Preescolar'), ('2', 'Primaria'), ('3', 'Secundaria'), ('4', 'Preparatoria')])),
                ('grado', models.PositiveIntegerField(choices=[('1', '1°'), ('2', '2°'), ('3', '3°'), ('4', '4°'), ('5', '5°'), ('6', '6°')])),
            ],
        ),
    ]
