# Generated by Django 4.2.23 on 2025-07-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_niveleducativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveleducativo',
            name='grado',
            field=models.PositiveIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°')]),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(1, 'Preescolar'), (2, 'Primaria'), (3, 'Secundaria'), (4, 'Preparatoria')]),
        ),
    ]
