# Generated by Django 4.2.23 on 2025-07-30 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_niveleducativo_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveleducativo',
            name='grupo',
            field=models.PositiveIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], default=1),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='grado',
            field=models.PositiveIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°')], default=1),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(1, 'Preescolar'), (2, 'Primaria'), (3, 'Secundaria'), (4, 'Preparatoria')], default=1),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=100)),
                ('materno', models.CharField(max_length=100)),
                ('nivelEducativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveleducativo')),
                ('tutorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
    ]
