# Generated by Django 4.2.23 on 2025-08-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuarios_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnos',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='niveleducativo',
            options={'verbose_name': 'Nivel Educativo', 'verbose_name_plural': 'Niveles Educativos'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='materno',
            field=models.CharField(max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nivelEducativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveleducativo', verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='tutorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(max_length=100, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='grado',
            field=models.PositiveIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°')], default=1, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='grupo',
            field=models.PositiveIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], default=1, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(1, 'Preescolar'), (2, 'Primaria'), (3, 'Secundaria'), (4, 'Preparatoria')], default=1, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='parentesco',
            field=models.CharField(max_length=50, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='materno',
            field=models.CharField(max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
